# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='date_joined',
            new_name='pub_date',
        ),
    ]
