# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(null=True, upload_to='biz-image/'),
        ),
    ]
