# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20180527_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
