# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_newsletterrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbourhood'),
        ),
    ]
