# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20180527_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(null=True),
        ),
    ]
